//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHH_Store.Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public long id_usuario { get; set; }
        public string usuario { get; set; }
        public string contraseña { get; set; }
        public string legajo { get; set; }
        public Nullable<bool> activo { get; set; }
        public long admin_personaID { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
