//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHH_Store.Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Administrador = new HashSet<Administrador>();
            this.Postulante = new HashSet<Postulante>();
        }
    
        public long idPersona { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string nacionalidad { get; set; }
        public string dni { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string telefono { get; set; }
        public string domicilio { get; set; }
        public string mail { get; set; }
        public string telFijo { get; set; }
        public string telAlternativo { get; set; }
        public Nullable<bool> hijos { get; set; }
        public Nullable<int> cantHijos { get; set; }
        public byte[] foto { get; set; }
        public bool activa { get; set; }
        public long disponibilidadID { get; set; }
        public long estadoCivilID { get; set; }
        public long sexoID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Administrador> Administrador { get; set; }
        public virtual Disponibilidad Disponibilidad { get; set; }
        public virtual EstadoCivil EstadoCivil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postulante> Postulante { get; set; }
        public virtual Sexo Sexo { get; set; }
    }
}
