//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHH_Store.Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postulante
    {
        public long idPostulante { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public long Perfil_id { get; set; }
        public long Persona_Id { get; set; }
        public bool activo { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
